### ISSUE TITLE
javascript : create a todo array of object  to store the todos data

### ISSUE THREAD

**Issue by osbc2022** [osbc2022/to-do-list#3]
To do :-
- [ ] link a external javascript file to `index.html` in the head with `async defer` attributes 
- [ ] create a object todo(name) it should me mutable don't make a const
- [ ]  it is going to be a array of object
- [ ]  the object will contain 2 values todo(string) and isCompelete(boolean)

**Comment by amitanshusahu** [comment]
i would like to work on this 😄

**Comment by osbc2022** [comment]
ok @amitanshusahu  go for it :+1:
